### ISSUE TITLE
ONNX 1.5.0 install didn't work

### ISSUE THREAD

**Issue by pcotret** [QDucasse/nn_benchmark#10]
```bash
$ sudo pip3 install onnx==1.5.0
```
Output:
```
Collecting onnx==1.5.0
  Using cached onnx-1.5.0.tar.gz (3.0 MB)
Requirement already satisfied: numpy in /usr/local/lib/python3.8/dist-packages (from onnx==1.5.0) (1.18.0)
Requirement already satisfied: protobuf in /usr/local/lib/python3.8/dist-packages (from onnx==1.5.0) (3.13.0)
Requirement already satisfied: six in /usr/lib/python3/dist-packages (from onnx==1.5.0) (1.14.0)
Requirement already satisfied: typing-extensions>=3.6.2.1 in /usr/local/lib/python3.8/dist-packages (from onnx==1.5.0) (3.7.4.3)
Requirement already satisfied: typing>=3.6.4 in /usr/local/lib/python3.8/dist-packages (from onnx==1.5.0) (3.7.4.3)
Requirement already satisfied: setuptools in /usr/lib/python3/dist-packages (from protobuf->onnx==1.5.0) (45.2.0)
Building wheels for collected packages: onnx
  Building wheel for onnx (setup.py) ... error
  ERROR: Command errored out with exit status 1:
   command: /usr/bin/python3 -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-kl6a3fbk/onnx/setup.py'"'"'; __file__='"'"'/tmp/pip-install-kl6a3fbk/onnx/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' bdist_wheel -d /tmp/pip-wheel-fk8eppdr
       cwd: /tmp/pip-install-kl6a3fbk/onnx/
  Complete output (117 lines):
  fatal: not a git repository (or any of the parent directories): .git
  running bdist_wheel
  running build
  running build_py
  running create_version
  running cmake_build
  -- The C compiler identification is GNU 9.3.0
  -- The CXX compiler identification is GNU 9.3.0
  -- Check for working C compiler: /usr/bin/cc
  -- Check for working C compiler: /usr/bin/cc -- works
  -- Detecting C compiler ABI info
  -- Detecting C compiler ABI info - done
  -- Detecting C compile features
  -- Detecting C compile features - done
  -- Check for working CXX compiler: /usr/bin/c++
  -- Check for working CXX compiler: /usr/bin/c++ -- works
  -- Detecting CXX compiler ABI info
  -- Detecting CXX compiler ABI info - done
  -- Detecting CXX compile features
  -- Detecting CXX compile features - done
  -- Found Protobuf: /usr/local/lib/libprotobuf.so (found version "3.13.0")
  -- Found PythonInterp: /usr/bin/python3 (found version "3.8.5")
  -- Found PythonLibs: /usr/lib/x86_64-linux-gnu/libpython3.8.so
  --
  -- ******** Summary ********
  --   CMake version         : 3.16.3
  --   CMake command         : /usr/bin/cmake
  --   System                : Linux
  --   C++ compiler          : /usr/bin/c++
  --   C++ compiler version  : 9.3.0
  --   CXX flags             :  -Wnon-virtual-dtor
  --   Build type            : Release
  --   Compile definitions   :
  --   CMAKE_PREFIX_PATH     :
  --   CMAKE_INSTALL_PREFIX  : /usr/local
  --   CMAKE_MODULE_PATH     : /usr/local/share/cmake/pybind11
  --
  --   ONNX version          : 1.5.0
  --   ONNX NAMESPACE        : onnx
  --   ONNX_BUILD_TESTS      : OFF
  --   ONNX_BUILD_BENCHMARKS : OFF
  --   ONNX_USE_LITE_PROTO   : OFF
  --   ONNXIFI_DUMMY_BACKEND : OFF
  --   ONNXIFI_ENABLE_EXT    : OFF
  --
  --   Protobuf compiler     : /usr/local/bin/protoc
  --   Protobuf includes     : /usr/local/include
  --   Protobuf libraries    : /usr/local/lib/libprotobuf.so
  --   BUILD_ONNX_PYTHON     : ON
  --     Python version      :
  --     Python executable   : /usr/bin/python3
  --     Python includes     : /usr/include/python3.8
  -- Configuring done
  -- Generating done
  -- Build files have been written to: /tmp/pip-install-kl6a3fbk/onnx/.setuptools-cmake-build
  Scanning dependencies of target onnxifi_loader
  Scanning dependencies of target gen_onnx_proto
  Scanning dependencies of target onnxifi_dummy
  [  1%] Building C object CMakeFiles/onnxifi_loader.dir/onnx/onnxifi_loader.c.o
  [  5%] Building C object CMakeFiles/onnxifi_dummy.dir/onnx/onnxifi_dummy.c.o
  [  5%] Running gen_proto.py on onnx/onnx.in.proto
  /tmp/pip-install-kl6a3fbk/onnx/onnx/onnxifi_dummy.c: In function ‘onnxGetExtensionFunctionAddress’:
  /tmp/pip-install-kl6a3fbk/onnx/onnx/onnxifi_dummy.c:173:21: warning: assignment to ‘onnxExtensionFunctionPointer’ {aka ‘int (*)(void)’} from incompatible pointer type ‘onnxStatus (*)(void *, const char *, onnxStatus (**)(void))’ {aka ‘int (*)(void *, const char *, int (**)(void))’} [-Wincompatible-pointer-types]
    173 |           *function = &onnxGetExtensionFunctionAddress;
        |                     ^
  /tmp/pip-install-kl6a3fbk/onnx/onnx/onnxifi_dummy.c:176:21: warning: assignment to ‘onnxExtensionFunctionPointer’ {aka ‘int (*)(void)’} from incompatible pointer type ‘onnxStatus (*)(void *, uint32_t,  const onnxTensorDescriptorV1 *, uint32_t,  const onnxTensorDescriptorV1 *, onnxMemoryFenceV1 *)’ {aka ‘int (*)(void *, unsigned int,  const struct onnxTensorDescriptorV1 *, unsigned int,  const struct onnxTensorDescriptorV1 *, struct onnxMemoryFenceV1 *)’} [-Wincompatible-pointer-types]
    176 |           *function = &onnxSetIOAndRunGraph;
        |                     ^
  Processing /tmp/pip-install-kl6a3fbk/onnx/onnx/onnx.in.proto
  Writing /tmp/pip-install-kl6a3fbk/onnx/.setuptools-cmake-build/onnx/onnx-ml.proto
  Writing /tmp/pip-install-kl6a3fbk/onnx/.setuptools-cmake-build/onnx/onnx-ml.proto3
  generating /tmp/pip-install-kl6a3fbk/onnx/.setuptools-cmake-build/onnx/onnx_pb.py
  [  8%] Running C++ protocol buffer compiler on /tmp/pip-install-kl6a3fbk/onnx/.setuptools-cmake-build/onnx/onnx-ml.proto
  [  8%] Linking C static library libonnxifi_loader.a
  --python_out: onnx/onnx-ml.proto: Unknown generator option: dllexport_decl
  make[2]: *** [CMakeFiles/gen_onnx_proto.dir/build.make:62: onnx/onnx-ml.pb.cc] Error 1
  make[1]: *** [CMakeFiles/Makefile2:250: CMakeFiles/gen_onnx_proto.dir/all] Error 2
  make[1]: *** Waiting for unfinished jobs....
  [ 10%] Linking C shared library libonnxifi_dummy.so
  [ 10%] Built target onnxifi_loader
  [ 10%] Built target onnxifi_dummy
  make: *** [Makefile:130: all] Error 2
  Traceback (most recent call last):
    File "<string>", line 1, in <module>
    File "/tmp/pip-install-kl6a3fbk/onnx/setup.py", line 312, in <module>
      setuptools.setup(
    File "/usr/lib/python3/dist-packages/setuptools/__init__.py", line 144, in setup
      return distutils.core.setup(**attrs)
    File "/usr/lib/python3.8/distutils/core.py", line 148, in setup
      dist.run_commands()
    File "/usr/lib/python3.8/distutils/dist.py", line 966, in run_commands
      self.run_command(cmd)
    File "/usr/lib/python3.8/distutils/dist.py", line 985, in run_command
      cmd_obj.run()
    File "/usr/lib/python3/dist-packages/wheel/bdist_wheel.py", line 223, in run
      self.run_command('build')
    File "/usr/lib/python3.8/distutils/cmd.py", line 313, in run_command
      self.distribution.run_command(command)
    File "/usr/lib/python3.8/distutils/dist.py", line 985, in run_command
      cmd_obj.run()
    File "/usr/lib/python3.8/distutils/command/build.py", line 135, in run
      self.run_command(cmd_name)
    File "/usr/lib/python3.8/distutils/cmd.py", line 313, in run_command
      self.distribution.run_command(command)
    File "/usr/lib/python3.8/distutils/dist.py", line 985, in run_command
      cmd_obj.run()
    File "/tmp/pip-install-kl6a3fbk/onnx/setup.py", line 206, in run
      self.run_command('cmake_build')
    File "/usr/lib/python3.8/distutils/cmd.py", line 313, in run_command
      self.distribution.run_command(command)
    File "/usr/lib/python3.8/distutils/dist.py", line 985, in run_command
      cmd_obj.run()
    File "/tmp/pip-install-kl6a3fbk/onnx/setup.py", line 200, in run
      subprocess.check_call(build_args)
    File "/usr/lib/python3.8/subprocess.py", line 364, in check_call
      raise CalledProcessError(retcode, cmd)
  subprocess.CalledProcessError: Command '['/usr/bin/cmake', '--build', '.', '--', '-j', '8']' returned non-zero exit status 2.
  ----------------------------------------
  ERROR: Failed building wheel for onnx
  Running setup.py clean for onnx
Failed to build onnx
Installing collected packages: onnx
    Running setup.py install for onnx ... error
    ERROR: Command errored out with exit status 1:
     command: /usr/bin/python3 -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-kl6a3fbk/onnx/setup.py'"'"'; __file__='"'"'/tmp/pip-install-kl6a3fbk/onnx/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record /tmp/pip-record-yf_azwz3/install-record.txt --single-version-externally-managed --compile --install-headers /usr/local/include/python3.8/onnx
         cwd: /tmp/pip-install-kl6a3fbk/onnx/
    Complete output (87 lines):
    fatal: not a git repository (or any of the parent directories): .git
    running install
    running build
    running build_py
    running create_version
    running cmake_build
    --
    -- ******** Summary ********
    --   CMake version         : 3.16.3
    --   CMake command         : /usr/bin/cmake
    --   System                : Linux
    --   C++ compiler          : /usr/bin/c++
    --   C++ compiler version  : 9.3.0
    --   CXX flags             :  -Wnon-virtual-dtor
    --   Build type            : Release
    --   Compile definitions   :
    --   CMAKE_PREFIX_PATH     :
    --   CMAKE_INSTALL_PREFIX  : /usr/local
    --   CMAKE_MODULE_PATH     : /usr/local/share/cmake/pybind11
    --
    --   ONNX version          : 1.5.0
    --   ONNX NAMESPACE        : onnx
    --   ONNX_BUILD_TESTS      : OFF
    --   ONNX_BUILD_BENCHMARKS : OFF
    --   ONNX_USE_LITE_PROTO   : OFF
    --   ONNXIFI_DUMMY_BACKEND : OFF
    --   ONNXIFI_ENABLE_EXT    : OFF
    --
    --   Protobuf compiler     : /usr/local/bin/protoc
    --   Protobuf includes     : /usr/local/include
    --   Protobuf libraries    : /usr/local/lib/libprotobuf.so
    --   BUILD_ONNX_PYTHON     : ON
    --     Python version      :
    --     Python executable   : /usr/bin/python3
    --     Python includes     : /usr/include/python3.8
    -- Configuring done
    -- Generating done
    -- Build files have been written to: /tmp/pip-install-kl6a3fbk/onnx/.setuptools-cmake-build
    [  3%] Built target onnxifi_loader
    [  5%] Running C++ protocol buffer compiler on /tmp/pip-install-kl6a3fbk/onnx/.setuptools-cmake-build/onnx/onnx-ml.proto
    [  8%] Built target onnxifi_dummy
    Scanning dependencies of target onnxifi_wrapper
    --python_out: onnx/onnx-ml.proto: Unknown generator option: dllexport_decl
    [ 10%] Building C object CMakeFiles/onnxifi_wrapper.dir/onnx/onnxifi_wrapper.c.o
    make[2]: *** [CMakeFiles/gen_onnx_proto.dir/build.make:62: onnx/onnx-ml.pb.cc] Error 1
    make[1]: *** [CMakeFiles/Makefile2:250: CMakeFiles/gen_onnx_proto.dir/all] Error 2
    make[1]: *** Waiting for unfinished jobs....
    [ 12%] Linking C shared module libonnxifi.so
    [ 12%] Built target onnxifi_wrapper
    make: *** [Makefile:130: all] Error 2
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-install-kl6a3fbk/onnx/setup.py", line 312, in <module>
        setuptools.setup(
      File "/usr/lib/python3/dist-packages/setuptools/__init__.py", line 144, in setup
        return distutils.core.setup(**attrs)
      File "/usr/lib/python3.8/distutils/core.py", line 148, in setup
        dist.run_commands()
      File "/usr/lib/python3.8/distutils/dist.py", line 966, in run_commands
        self.run_command(cmd)
      File "/usr/lib/python3.8/distutils/dist.py", line 985, in run_command
        cmd_obj.run()
      File "/usr/lib/python3/dist-packages/setuptools/command/install.py", line 61, in run
        return orig.install.run(self)
      File "/usr/lib/python3.8/distutils/command/install.py", line 589, in run
        self.run_command('build')
      File "/usr/lib/python3.8/distutils/cmd.py", line 313, in run_command
        self.distribution.run_command(command)
      File "/usr/lib/python3.8/distutils/dist.py", line 985, in run_command
        cmd_obj.run()
      File "/usr/lib/python3.8/distutils/command/build.py", line 135, in run
        self.run_command(cmd_name)
      File "/usr/lib/python3.8/distutils/cmd.py", line 313, in run_command
        self.distribution.run_command(command)
      File "/usr/lib/python3.8/distutils/dist.py", line 985, in run_command
        cmd_obj.run()
      File "/tmp/pip-install-kl6a3fbk/onnx/setup.py", line 206, in run
        self.run_command('cmake_build')
      File "/usr/lib/python3.8/distutils/cmd.py", line 313, in run_command
        self.distribution.run_command(command)
      File "/usr/lib/python3.8/distutils/dist.py", line 985, in run_command
        cmd_obj.run()
      File "/tmp/pip-install-kl6a3fbk/onnx/setup.py", line 200, in run
        subprocess.check_call(build_args)
      File "/usr/lib/python3.8/subprocess.py", line 364, in check_call
        raise CalledProcessError(retcode, cmd)
    subprocess.CalledProcessError: Command '['/usr/bin/cmake', '--build', '.', '--', '-j', '8']' returned non-zero exit status 2.
    ----------------------------------------
ERROR: Command errored out with exit status 1: /usr/bin/python3 -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-kl6a3fbk/onnx/setup.py'"'"'; __file__='"'"'/tmp/pip-install-kl6a3fbk/onnx/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record /tmp/pip-record-yf_azwz3/install-record.txt --single-version-externally-managed --compile --install-headers /usr/local/include/python3.8/onnx Check the logs for full command output.
```

**Comment by pcotret** [comment]
It's working with this PR (which hasn't been merged): https://github.com/onnx/onnx/pull/2482
